### ISSUE TITLE
Consejo

### ISSUE THREAD

**Issue by santigutman** [pdepjm/2024-tp0-presentacion-LautaroPingitore#3]
Buenas! Podrías dejar un poco de espacio en el texto para que sea mas legible. Saludos!

**Comment by LautaroPingitore** [comment]
Hola Santi, ahí trate de separarlo por cada subtema, gracias por el consejo y avísame que te parece y si ya es mas fácil de leer

**Comment by santigutman** [comment]
Ahí se lee todo excelente, buen trabajo!
